export * from './tipos.ts'
export * from './pessoas.ts'
export * from './horario.ts'
export { DIAS_AVISO, resolverS2, validarAvisoNaAgenda, type ValidacaoAgenda } from './resolver.ts'
export * from './atendimento.ts'
